name: Provision and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  provision:
    name: Deploy Bicep Template
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          
    - name: Create Resource Group (if needed)
      run: |
        az group create --name ${{ secrets.AZURE_RG_NAME }} --location ${{ secrets.AZURE_LOCATION }}

    - name: Deploy Bicep
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RG_NAME }} \
          --template-file main.bicep \
          --parameters appName=${{ secrets.AZURE_WEBAPP_NAME }}

  # build-and-deploy:
    # name: Build and Deploy Angular App
    # runs-on: ubuntu-latest
    # needs: provision

    # steps:
    # - name: Checkout Code
      # uses: actions/checkout@v3

    # - name: Setup Node.js
      # uses: actions/setup-node@v3
      # with:
        # node-version: '18'

    # - name: Install Dependencies & Build Angular App
      # run: |
        # npm ci
        # npm run build -- --configuration production

    # - name: Deploy to Azure Web App
      # uses: azure/webapps-deploy@v2
      # with:
        # app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        # slot-name: 'production'
        # publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        # package: dist/your-angular-folder-name
